### ISSUE TITLE
게이트 키퍼 계정 생성 관련

### ISSUE THREAD

**Issue by TabloNi** [osamhack2021/IoT_GateKeyPer_Keeper#19]
### 게이트 키퍼 깃북 생성을 위하여 공식 계정 및 깃북 계정 생성이 필요할것으로 사료됨

- #### 방안 1 : 구글 계정을 통해 공식 계정 생성. 그 후 해당 계정을 통해 깃북 계정 연결뒤 각자의 깃북 계정을 초대하여 작성

- #### 방안 2 : 도메인을 하나 파서(혹은 기존의 도메인) 해당 도메인을 통해 공식 계정 생성. 그 후 깃북 계정도 사설로 생성한 뒤 각자의 깃북 계정을 초대하여 작성

> 방안 1 : 계정 생성 및 관리 측면에서는 유리할것이라 판단
> 방안 2 : 사설 도메인이 있을 경우 해당 도메인과 연결하기 유리할것으로 판단

@BoksungOh 해당 부분에 대하여 답변을 주시고 깃북 계정을 말씀해 주시면, 관련 내용 작업 및 초대 후 이슈 닫도록 하겠습니다!

**Comment by BoksungOh** [comment]
1번안으로, gitbook 계정을 만들었습니다. 
boksung@sol-dynamics.com (G-mail 연동) 으로 계정 만들었습니다!

**Comment by TabloNi** [comment]
2021년 9월 26일에 멘토링을 받은 것을 기점으로, 프로젝트에 관련된 모든 이슈는 노션으로 옮겨지게 되었습니다.
하단의 링크를 통하여 Project/이슈 탭을 이용 바랍니다.

감사합니다.

### **접속 링크 : https://bit.ly/gatekeyper_notion**
