### ISSUE TITLE
크래들 테스트베드 구성 및 개발

### ISSUE THREAD

**Issue by BoksungOh** [osamhack2021/IoT_GateKeyPer_Keeper#20]
Key와 Lock의 ID 조절과 지문인식 권한을 부여하기 위한 크래들의 테스트베드를 구축한다.
 - 1차 : TinkerCad를 이용한 구축
 - 2차 : 물리적 환경에서 가-구축

**Comment by TabloNi** [comment]
2021년 9월 26일에 멘토링을 받은 것을 기점으로, 프로젝트에 관련된 모든 이슈는 노션으로 옮겨지게 되었습니다.
하단의 링크를 통하여 Project/이슈 탭을 이용 바랍니다.

감사합니다.

### **접속 링크 : https://bit.ly/gatekeyper_notion**
