### ISSUE TITLE
Key-Lock-Cradle 제품의 3D모델링 진행

### ISSUE THREAD

**Issue by BoksungOh** [osamhack2021/IoT_GateKeyPer_Keeper#21]
회로 구성요소를 담고, 구동 시연을 하기위한 제품의 3D모델링 진행.

1. 기존 구매 구성요소를 3D로 옮김 (10월 1일 예상) ->9월 30일로 앞당기도록 조정
2. 구매부품을 바탕으로 3D 모델링을 진행(10월 4일 예상) -> 10월 1일 앞당기도록 조정
3. 3D 모델링 요소를 3D 프린팅 (10월 7~8일 예상) -> 10월 6일에 도착할 수 있도록 조정
4. 회로 및 제품 구성, 펌웨어 담기 (소요시간 1일 내외)

**Comment by BoksungOh** [comment]
1. 디바이스마트 제품군 도착완료
2. Aliexpress 제품군 커넥터 도착 완료, 
3. Aliexpress 제품군 DC3V 도어락 제품군 27일 도착 예정.
 - 예상 출타 일자인 29일에 모두 설계 완료하여 30일경 3D 프린팅 올리는 것 목표.

**Comment by TabloNi** [comment]
2021년 9월 26일에 멘토링을 받은 것을 기점으로, 프로젝트에 관련된 모든 이슈는 노션으로 옮겨지게 되었습니다.
하단의 링크를 통하여 Project/이슈 탭을 이용 바랍니다.

감사합니다.

### **접속 링크 : https://bit.ly/gatekeyper_notion**
