### ISSUE TITLE
크래들-PC환경용 UI/UX 구축하기

### ISSUE THREAD

**Issue by BoksungOh** [osamhack2021/IoT_GateKeyPer_Keeper#22]
크래들의 Serial을 받아오고, 뿌려줄 웹 / 로컬 UI/UX구성 필요.
파이썬으로 작업 예정

**Comment by BoksungOh** [comment]
아두이노 - 파이썬 : 컴포트 긁어서 그대로 웹에 도시하기
https://all-share-source-code.tistory.com/9

PS. UX/UI는 Django를 이용하는것이 어떨지 고민중.
-> 표 구성요소만 가져와서 만들기

**Comment by BoksungOh** [comment]
UI 부분은 하기 내용을 참고하면 될듯함.
** Django 오픈소스 데이터 테이블 코드 있음! 해당 내용 조정하여 만들면 될듯
[ 랜딩 페이지 ] : https://django-datatables-sample.appseed.us/
[ 해당 페이지 git ] : https://github.com/app-generator/django-datatables-sample

**Comment by TabloNi** [comment]
2021년 9월 26일에 멘토링을 받은 것을 기점으로, 프로젝트에 관련된 모든 이슈는 노션으로 옮겨지게 되었습니다.
하단의 링크를 통하여 Project/이슈 탭을 이용 바랍니다.

감사합니다.

### **접속 링크 : https://bit.ly/gatekeyper_notion**
