### ISSUE TITLE
프로젝트 깃북 생성

### ISSUE THREAD

**Issue by TabloNi** [osamhack2021/IoT_GateKeyPer_Keeper#24]
### 프로젝트의 깃북 생성(Ver 0.0.1)을 완료하였습니다.

현재 목차 및 세부 목차에 대하여 작업이 진행되어 있고, 세부 내용 서술 및 목차 수정 등을 진행 중입니다.
설정한 목차는 하단에 서술해 두었고, 예시 링크 및 들어가면 될 내용을 간단하게 서술해 두었습니다.
필요시 자유로운 피드백 부탁드립니다!

**_현재 고민점_**
> 문서의 방향성에 대하여 더 고민을 해봐야 할거 같음(개발 문서? 프로젝트 문서?)
> 문서의 방향성에 따라 사용 시나리오의 존재가 불투명함.
> 시스템 시나리오와 How to use의 명확한 구분이 필요.

### 메인

게이트 키퍼 소개
팀 설명
관련 링크

#### 프로젝트 개발 동기
현재 너무 불편한 키 상태
-> 보안 목적의 키 사용이 오히려 보안을 해치고 있음

#### 프로젝트 개발 목표
~~한 솔루션을 제작할 예정
https://kookmoban.gitbook.io/osam/undefined-4/undefined-2

#### 프로젝트 개발 일정
개발 일정
https://kookmoban.gitbook.io/osam/undefined-4/undefined-3

#### 프로젝트 구조
전체적인 프로젝트 구조에 대하여 서술
(이미지 한장)
자물쇠와 키가 있고, 각 키가 크래들과 연결되고 크래들이 PC와 연결되어 진행되는 느낌
https://specialwarrior-specialforces.gitbook.io/specialforces/specialforces-3/undefined-3

#### 시스템 구성
시스템의 구성 및 기술 스택에 대하여 설명함 (이미지로)

https://kookmoban.gitbook.io/osam/technical-note/undefined-5

#### 구성품 구성 요소

https://specialwarrior-specialforces.gitbook.io/specialforces/how-to-build/iot/situps-device

회로, 주고 받는 데이터 양식, 기능 별로 표로 정리하여 서술한다.

	⁃	자물쇠 : ~~ 한 부품들로 구성이 되고 ~ 신호를 받으면 열리고 ~한 신호를 받으면 닫히고 같은 시스템 적인 부분을 다 설명
	⁃	키 : //
	⁃	크래들 : //
	⁃	웹 : ~~ 스택을 사용해서 ~~~ 해서 구성함

#### 시스템 시나리오

https://kookmoban.gitbook.io/osam/technical-note/undefined

	⁃	초기 등록 -> 처음에 키를 등록하는 법과 이때의 데이터의 흐름

	⁃	자물쇠 열기/잠그기 -> 어떤 값을 주면 어떤식으로 열리고 어떤식으로 하면 또 닫히고

	⁃	권한 설정하기 -> 어떤 값을 주면 파란색이 되고 어떤 값을 주면 주황색이 되는지

	⁃	크래들 연결하기 -> 크래들과 키를 연결하면 어떤 데이터들이 어떤 송수신 방법을 통해 교환이 진행되고, 크래들은 PC와 어떤 데이터를 주고 받는지

#### 시스템 기능

https://kookmoban.gitbook.io/osam/technical-note/undefined-1/iot

	⁃	IoT 
	⁃	Web

#### 사용자 사용 시나리오
사용자(병사)의 입장에서 한 3개 정도로 시나리오를 만들어서 사용성에 대하여 설명한다.

#### 관리자 사용 시나리오
관리자(간부)의 입장에서 3개정도 똑같이 설명한다.

###  How to build

https://kookmoban.gitbook.io/osam/how-to-build/iot

####  IOT 
회로, 코드, 빌드 방법 등

####  WEB
코드, 빌드 방법 등

###  How to use

https://kookmoban.gitbook.io/osam/how-to-use/undefined-1

#### 초기 설정
초기에 하드웨어, 웹을 설정 하는 법을 서술한다.

#### 자물쇠 열기
자물쇠를 여는 방법에 대하여 서술한다.

#### 자물쇠 잠그기
자물쇠를 닫는 방법에 대하여 서술한다.

#### 권한 설정하기
권한을 설정하는 법에 대하여 서술한다.

#### 로그 확인하기
로그를 확인 하는 법에 대하여 서술한다.

### 라이센스

https://kookmoban.gitbook.io/osam/license/web

####  IoT License

**Comment by TabloNi** [comment]
https://osam-gatekeyper.gitbook.io/gatekeyper/

현재 작업중인 깃북 링크입니다!

**Comment by BoksungOh** [comment]
확인했습니다! 30일경, 모델링 자료가 나올듯한데 그때 구성요소별로 사진찍어서 분류해보며 조정 해보겠습니다!

**Comment by TabloNi** [comment]
2021년 9월 26일에 멘토링을 받은 것을 기점으로, 프로젝트에 관련된 모든 이슈는 노션으로 옮겨지게 되었습니다.
하단의 링크를 통하여 Project/이슈 탭을 이용 바랍니다.

감사합니다.

### **접속 링크 : https://bit.ly/gatekeyper_notion**
