### ISSUE TITLE
테스트베드 하드웨어 구성

### ISSUE THREAD

**Issue by BoksungOh** [osamhack2021/IoT_GateKeyPer_Keeper#4]
9월 14일 발송하여, 9월 16일 ~ 26일까지 사용하게 될 테스트 베드 제품을 구성하였습니다.
링크 : [테스트베드 구축 방안 및 이슈](https://github.com/osamhack2021/IoT-App-GateKeyPer/blob/master/IoT/%ED%95%98%EB%93%9C%EC%9B%A8%EC%96%B4%20%EA%B5%AC%EC%84%B1%EC%9A%94%EC%86%8C.md#%EC%B4%88%EA%B8%B0-%ED%85%8C%EC%8A%A4%ED%8A%B8%EB%B2%A0%EB%93%9C-%EA%B5%AC%EC%B6%95-%EB%B0%A9%EC%95%88)

내부에 담길 코드의 구성요소는 이쪽에서 볼수있습니다!
링크 : [펌웨어 흐름](https://github.com/osamhack2021/IoT-App-GateKeyPer/blob/master/IoT/%ED%8E%8C%EC%9B%A8%EC%96%B4%20%EA%B0%9C%EB%B0%9C%20%EA%B5%AC%EC%84%B1%EC%9A%94%EC%86%8C.md#%ED%82%A4-%EC%9E%90%EB%AC%BC%EC%87%A0-%EA%B8%B0%EB%8A%A5%EC%97%90-%EB%8C%80%ED%95%9C-%EC%82%AC%EC%9A%A9-%ED%9D%90%EB%A6%84%EA%B3%BC-ui)

**Comment by BoksungOh** [comment]
교육키트 공군 주소지로 보냈습니다! 
회로 구성 방법은 도착 예정시간인 16일 내외에 코멘트 달겠습니다!
[아두이노 교육 키트](https://www.devicemart.co.kr/goods/view?no=1264627)

**Comment by BoksungOh** [comment]
교육키트를 다음과 같이 구성해서 프로토를 제작하려 합니다!
회로 구성 참고 : [Tinkercad 회로도 구성](https://www.tinkercad.com/things/g2GT9QLMZIN)
 -> 시뮬레이션을 클릭하면 확대 및 메모 확인을 할 수 있습니다!

[프리뷰 이미지]
![프리뷰 이미지](https://user-images.githubusercontent.com/89676600/133268746-27058418-a329-44ae-84f9-2f5d041e9c73.png)


각 모듈 및 I2C 통신에 관한 예제를 링크하였으니 개발환경 테스트에 참고바랍니다!
1. [부저 코딩 참고](https://m.blog.naver.com/PostView.naver?isHttpsRedirect=true&blogId=geniusus&logNo=221549772862)
2. [1:N I2C 통신 참고](https://kocoafab.cc/tutorial/view/452)
3. [스위치 코딩 참고](https://kocoafab.cc/tutorial/view/526)
4. [3색 LED 코딩 참고](https://kocoafab.cc/tutorial/view/725)

**Comment by BoksungOh** [comment]
발송한 제품 도착 후, 회로 구성/모듈 코딩 진행에 문제가 없다면 본 이슈를 닫아주세요!

**Comment by BoksungOh** [comment]
제 테스트베드 환경은 21. 09. 17. 오후 중, 보안담당관님과의 상담 이후 구축이 완료될 예정입니다.

**Comment by TabloNi** [comment]
물품 전량 수령 후 확인 완료했습니다!

제 테스트베드 환경은 21.09.19. 오후에 전후 세팅 완료되었고, 사지방 컴퓨터(부대내 보안 확인 통과) + 아두이노 2Set 환경입니다.
