### ISSUE TITLE
지난해 수상작 분석 및 영상 기획

### ISSUE THREAD

**Issue by TabloNi** [osamhack2021/IoT_GateKeyPer_Keeper#7]
https://www.youtube.com/channel/UCp-L48KrSB18I9yWnNoD69g/videos

상단의 사이트에 접속하여 수상작들의 프로젝트 분석 및 영상 편집 기법을 분석하고, GateKeyPer 프로젝트에 적용할 참고할만항 영상을 선출한다.

**Comment by TabloNi** [comment]
> https://www.youtube.com/channel/UCp-L48KrSB18I9yWnNoD69g/videos
> 
> 상단의 사이트에 접속하여 수상작들의 프로젝트 분석 및 영상 편집 기법을 분석하고, GateKeyPer 프로젝트에 적용할 참고할만항 영상을 선출한다.

https://youtu.be/Vmh0gduZzPU

https://youtu.be/V7LqATNFefc

상단의 두개의 영상이 GateKeyPer 프로젝트 설명 영상 방식에 적합할것으로 판명, 해당 영상을 분석하여 콘티를 제작하고 추후 프로젝트 완료 시에 세부 회의를 진행할 수 있도록 한다.

**Comment by TabloNi** [comment]
- https://youtu.be/Vmh0gduZzPU

- https://youtu.be/V7LqATNFefc

상단의 두개의 영상이 GateKeyPer 프로젝트 설명 영상 방식에 적합할것으로 판명, 해당 영상을 분석하여 콘티를 제작하고 추후 프로젝트 완료 시에 세부 회의를 진행할 수 있도록 한다.

**Comment by BoksungOh** [comment]
스마트폰 비대면 관리앱 소개영상(https://youtu.be/Vmh0gduZzPU)이 추후 저희가 하게될 영상 구성의 형태와 가장 비슷하네요!
특별한 배경 설명 소개 없이도 직관적으로 서비스를 이해하고 활용성을 평가할 수 있었습니다!

참고하면 좋을 내용을 기재해보자면, 
 - 시리얼로 확인을 하게되면, 본 영상에 비해 UI가 좋지 않으니 소개할 때 직관성이 떨어진다.
 - 웹으로 보여주니 좀더 멋져보인다! (생각보다 무선통신/LAN 을 쓰는것에 제약을 두진 않는느낌)

 => 이점을 참고하여, python 또는 실시간 무선통신을 사용하여 Wep으로 띄워주는것도 좋아보입니다.

**Comment by TabloNi** [comment]
2021년 9월 26일에 멘토링을 받은 것을 기점으로, 프로젝트에 관련된 모든 이슈는 노션으로 옮겨지게 되었습니다.
하단의 링크를 통하여 Project/이슈 탭을 이용 바랍니다.

감사합니다.

### **접속 링크 : https://bit.ly/gatekeyper_notion**
