### ISSUE TITLE
Projects 기능 안내

### ISSUE THREAD

**Issue by TabloNi** [osamhack2021/IoT_GateKeyPer_Keeper#8]
안녕하세요!

카톡으로 남겼는데 이미 폰을 내신 거 같으셔서 이슈 기능을 통해 내용 전달드립니다!

제가 저희 레포 안에 Projects 기능을 활성화시키고, 해당 부분을 크게 **'메인 프로젝트', 안드로이드', '하드웨어'** 부분으로 나누어서 분류하였습니다.

메인 프로젝트는 전체적인 프로젝트의 진행 사항을 정리하면 좋을 것 같고, 그 외에 하드웨어 및 앱 부분은 각각의 프로젝트에 정리하면 될 것 같습니다.

사용 방법은 기존의 트렐로와 유사하다 보면 될 것 같고, 타이틀 및 디스크립션 부분 자유럽게 수정해 주시면 될 것 같습니다!

감사합니다!

@BoksungOh **(확인 후 댓글 및 이슈 닫아주시면 감사드리겠습니다!)**

**Comment by BoksungOh** [comment]
@TabloNi  확인하였습니다!
완전히 Trello와 동일하여, 이질감없이 구성하고 작업할 수 있을듯합니다!
